const DEFAULT_CHASE_DISTANCE = 600;
const DEFAULT_ATTACK_DISTANCE = 40;
const DEFAULT_MOVE_SPEED = 50;
const ZERO_HEALTH = 0;
const ZERO_VELOCITY = 0;
const ZERO_DISTANCE = 0;
const ZERO_COOLDOWN = 0;
const MIN_DISTANCE = 0.0001;

export {
  DEFAULT_CHASE_DISTANCE,
  DEFAULT_ATTACK_DISTANCE,
  DEFAULT_MOVE_SPEED,
  ZERO_COOLDOWN,
  ZERO_DISTANCE,
  ZERO_HEALTH,
  ZERO_VELOCITY,
  MIN_DISTANCE,
};
