const MIN_FRAME_DURATION = 0.016;
const DEFAULT_FRAME_DURATION_MS = 100;
const MILLISECONDS_IN_SECOND = 1000;
const ZERO_DELTA = 0;
const MOVING_THRESHOLD = 1;
const ZERO_ANIMATION_TIMER = 0;
const ZERO_FRAMES = 0;
const MIN_COLUMNS = 1;
const OCTANTS = 8;
const OCTANT_RADIANS = Math.PI / 4;

export {
  MIN_FRAME_DURATION,
  DEFAULT_FRAME_DURATION_MS,
  MILLISECONDS_IN_SECOND,
  ZERO_DELTA,
  MOVING_THRESHOLD,
  ZERO_ANIMATION_TIMER,
  ZERO_FRAMES,
  MIN_COLUMNS,
  OCTANTS,
  OCTANT_RADIANS,
};
