const ZERO_EFFECT_TIME = 0;
const ZERO_TICK_TIMER = 0;
const ONE_TICK = 1;
const SPEED_BOOST_MULTIPLIER = 1.1;
const SLOW_BOOST_MULTIPLIER = 0.9;
const ZERO_EFFECTS = 0;
const ZERO_HEALTH = 0;

export {
  ZERO_EFFECT_TIME,
  ZERO_TICK_TIMER,
  ONE_TICK,
  SPEED_BOOST_MULTIPLIER,
  SLOW_BOOST_MULTIPLIER,
  ZERO_EFFECTS,
  ZERO_HEALTH,
};
