const DEFAULT_MAP_WIDTH = 800
const DEFAULT_MAP_HEIGHT = 600
const DEFAULT_CELL_SIZE = 64
const BORDER_INDEX = 0
const OBSTACLE_COUNT = 10
const OBSTACLE_PADDING = 50
const SPAWN_PADDING = 100
const PLAYER_SPAWN_X = 400
const PLAYER_SPAWN_Y = 300
const PLAYER_SPAWN_RADIUS = 15
const ENEMY_SPAWN_COUNT = 5
const ENEMY_SPAWN_RADIUS = 20
const OBSTACLE_SIZE = 64

export {
  DEFAULT_MAP_WIDTH,
  DEFAULT_MAP_HEIGHT,
  DEFAULT_CELL_SIZE,
  BORDER_INDEX,
  OBSTACLE_COUNT,
  OBSTACLE_PADDING,
  SPAWN_PADDING,
  PLAYER_SPAWN_X,
  PLAYER_SPAWN_Y,
  PLAYER_SPAWN_RADIUS,
  ENEMY_SPAWN_COUNT,
  ENEMY_SPAWN_RADIUS,
  OBSTACLE_SIZE,
}
