import worldSettings from '@/engine/settings/world-settings/world';

const DEFAULT_MAP_WIDTH = 800;
const DEFAULT_MAP_HEIGHT = 600;
const DEFAULT_CELL_SIZE = 64;
const BORDER_INDEX = 0;
const OBSTACLE_COUNT = worldSettings.bounds.width / 300;
const OBSTACLE_PADDING = 20;
const SPAWN_PADDING = -40;
const PLAYER_SPAWN_X = 400;
const PLAYER_SPAWN_Y = 300;
const PLAYER_SPAWN_RADIUS = 15;
const ENEMY_SPAWN_COUNT = 100;
const ENEMY_SPAWN_RADIUS = 20;
const OBSTACLE_SIZE = 256;

export {
  DEFAULT_MAP_WIDTH,
  DEFAULT_MAP_HEIGHT,
  DEFAULT_CELL_SIZE,
  BORDER_INDEX,
  OBSTACLE_COUNT,
  OBSTACLE_PADDING,
  SPAWN_PADDING,
  PLAYER_SPAWN_X,
  PLAYER_SPAWN_Y,
  PLAYER_SPAWN_RADIUS,
  ENEMY_SPAWN_COUNT,
  ENEMY_SPAWN_RADIUS,
  OBSTACLE_SIZE,
};
