const DEFAULT_BULLET_SPEED = 600;
const DEFAULT_AUTO_FIRE_RANGE = 100;
const DEFAULT_PLAYER_SPEED = 200;
const ZERO_DISTANCE = 0;
const ZERO_COOLDOWN = 0;
const PROJECTILE_LIFETIME = 2;
const PROJECTILE_RADIUS = 3;
const DEFAULT_BULLET_WIDTH = 1;
const DEFAULT_BULLET_HEIGHT = 1;
const MOVE_FLAG = 1;
const STOP_FLAG = 0;

const DEFAULT_XP_BOX_WIDTH = 2;
const DEFAULT_XP_BOX_HEIGHT = 2;

export {
  DEFAULT_BULLET_SPEED,
  DEFAULT_AUTO_FIRE_RANGE,
  DEFAULT_PLAYER_SPEED,
  ZERO_DISTANCE,
  ZERO_COOLDOWN,
  PROJECTILE_LIFETIME,
  PROJECTILE_RADIUS,
  DEFAULT_BULLET_WIDTH,
  DEFAULT_BULLET_HEIGHT,
  MOVE_FLAG,
  STOP_FLAG,
  DEFAULT_XP_BOX_WIDTH,
  DEFAULT_XP_BOX_HEIGHT,
};
