const MIN_RENDER_SIZE = 12;
const HEALTH_BAR_OFFSET = 6;
const DEFAULT_SCALE = 1;
const MIN_SOURCE_SIZE = 1;
const ZERO_FRAMES = 0;
const MIN_COLUMNS = 1;
const MIN_ROWS = 1;
const OBSTACLE_FILL_COLOR = 'rgba(120, 130, 140, 0.9)';
const DEFAULT_ENTITY_FILL_COLOR = 'rgba(255, 255, 255, 0.6)';
const HEALTH_HIGH_THRESHOLD = 0.5;
const HEALTH_MEDIUM_THRESHOLD = 0.25;
const HEALTH_COLOR_HIGH = '#48ff8a';
const HEALTH_COLOR_MEDIUM = '#ffe066';
const HEALTH_COLOR_LOW = '#ff4d6d';
const HEALTH_BAR_BACKGROUND = 'rgba(20, 20, 20, 0.8)';
const HEALTH_BAR_HEIGHT = 4;
const HEALTH_BAR_STROKE = 'rgba(0, 0, 0, 0.6)';

export {
  MIN_RENDER_SIZE,
  HEALTH_BAR_OFFSET,
  DEFAULT_SCALE,
  MIN_SOURCE_SIZE,
  ZERO_FRAMES,
  MIN_COLUMNS,
  MIN_ROWS,
  OBSTACLE_FILL_COLOR,
  DEFAULT_ENTITY_FILL_COLOR,
  HEALTH_HIGH_THRESHOLD,
  HEALTH_MEDIUM_THRESHOLD,
  HEALTH_COLOR_HIGH,
  HEALTH_COLOR_MEDIUM,
  HEALTH_COLOR_LOW,
  HEALTH_BAR_BACKGROUND,
  HEALTH_BAR_HEIGHT,
  HEALTH_BAR_STROKE,
};
