const DEFAULT_AREA_WIDTH = 400
const DEFAULT_SPAWN_BATCH_SIZE = 2
const DEFAULT_BASE_WAVE_SIZE = 16
const DEFAULT_WAVE_GROWTH_FACTOR = 1.35
const BOSS_WAVE_INTERVAL = 5

export {
  DEFAULT_AREA_WIDTH,
  DEFAULT_SPAWN_BATCH_SIZE,
  DEFAULT_BASE_WAVE_SIZE,
  DEFAULT_WAVE_GROWTH_FACTOR,
  BOSS_WAVE_INTERVAL,
}
