const DEFAULT_AREA_WIDTH = 400;
const DEFAULT_SPAWN_BATCH_SIZE = 10;
const DEFAULT_SPAWN_BURST_INTERVAL = 8;
const DEFAULT_SPAWN_BURST_SIZE = 8;
const DEFAULT_BASE_WAVE_SIZE = 30;
const DEFAULT_WAVE_GROWTH_FACTOR = 1.25;
const BOSS_WAVE_INTERVAL = 5;

export {
  DEFAULT_AREA_WIDTH,
  DEFAULT_SPAWN_BATCH_SIZE,
  DEFAULT_BASE_WAVE_SIZE,
  DEFAULT_WAVE_GROWTH_FACTOR,
  DEFAULT_SPAWN_BURST_INTERVAL,
  DEFAULT_SPAWN_BURST_SIZE,
  BOSS_WAVE_INTERVAL,
};
