import { ForumComment, ForumTopic } from './types'

export const topics: ForumTopic[] = [
  {
    id: 1,
    title: 'Survival Tips: Best Tactics for Zone Navigation',
    author: 'Marked_One',
    authorBadge: 'Veteran',
    date: '10.10.25 14:32',
    likes: 42,
    comments: 18,
    tags: ['tactics', 'survival'],
    preview: 'Sharing my experience on difficult levels...',
  },
  {
    id: 2,
    title: 'Where to Find Best Weapons?',
    author: 'Zone_Hunter',
    authorBadge: 'Rookie',
    date: '10.10.25 12:15',
    likes: 27,
    comments: 12,
    tags: ['weapons', 'loot'],
    preview: 'Can someone tell me where to find the rifle in first zone?',
  },
  {
    id: 3,
    title: 'Bug: Zombies Stop Moving on Wave 15',
    author: 'Rad_Specialist',
    authorBadge: 'Veteran',
    date: '09.10.25 18:45',
    likes: 15,
    comments: 8,
    tags: ['bugs', 'help'],
    preview: 'Zombies freeze after wave 15, anyone else experiencing this?',
  },
  {
    id: 4,
    title: 'Artifacts Guide for Beginners',
    author: 'Anomaly_Seeker',
    authorBadge: 'Expert',
    date: '09.10.25 10:22',
    likes: 68,
    comments: 31,
    tags: ['guide', 'artifacts'],
    preview: 'Complete guide on collecting and using artifacts...',
  },
  {
    id: 5,
    title: 'Co-op Mode: When Will It Be Added?',
    author: 'Ghost_Runner',
    authorBadge: 'Rookie',
    date: '08.10.25 20:11',
    likes: 51,
    comments: 23,
    tags: ['features', 'multiplayer'],
    preview: 'Would be awesome to play with friends. Is multiplayer planned?',
  },
]

export const comments: ForumComment[] = [
  {
    id: 1,
    author: 'Zone_Hunter',
    date: '10.10.25 15:00',
    text: 'Great guide! Thanks for the tips.',
    avatar: '☢️',
  },
  {
    id: 2,
    author: 'Survivor_Alpha',
    date: '10.10.25 15:30',
    text: 'Will try these tactics tonight',
    avatar: '⚔️',
  },
]
